name: Python application - Tag

on:
  push:
    tags:
      - 'v*' # push on tags matching v*

env:
  SG_CLIENT_ID: ${{ secrets.SG_CLIENT_ID }}
  SG_SECRET_KEY: ${{ secrets.SG_SECRET_KEY }}

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest test.py
      # Download SourceGuard
      - name: Download SourceGuard
        run: |
          curl -o sourceguard-cli --location https://storage.googleapis.com/release-cli-prod/v0.0.106/linux/amd64/sourceguard-cli
          chmod u+x ./sourceguard-cli
      # Run sourceguard-cli
      - name: Run sourceguard-cli
        run: |
        ./sourceguard-cli -src ./
